import { GraphQLClient } from "graphql-request";
// Graphql api client
const auth_token =
  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE3MDYzNDEwNjQsImF1ZCI6WyJodHRwczovL2FwaS1hcC1zb3V0aC0xLmh5Z3JhcGguY29tL3YyL2NscnZveDVtaDBodGIwMXV0dWVtNWt5cXcvbWFzdGVyIiwibWFuYWdlbWVudC1uZXh0LmdyYXBoY21zLmNvbSJdLCJpc3MiOiJodHRwczovL21hbmFnZW1lbnQtYXAtc291dGgtMS5oeWdyYXBoLmNvbS8iLCJzdWIiOiI3YzViOWNmMy03MzkwLTRkNTMtYjZmMy0xZDZkODYzN2IxZTgiLCJqdGkiOiJjbHJ2cmV2bHAwZWZpMDFwZ2ZlNnE0NjZvIn0.PPD6IGwF8Jni8m_MfHchmtNgI7U0t10nk1HgiRy-08ArunSpxv_RK_kOnQkGvCuB49EQAojDlgl49DS5oII_-AEqGBPLPzsN_p3chE5NCU_Xa6Op93NsYyCMExb_dOaIFJi7xUIt-5aarTpv-E6LEh0Ah9Fctw5f6dUxGmpo33qDCAzqGySmJwezdWWpPSQBBL_sDceXf0AwHUQ1IxQXAsjwkyWPUdqqYT5EQugdiUq7gsbURFqtKWZEsfkcMRfnx1dzuI28ZvxiYsF9RJc1REjqoIbtYaZTWzoD3XZmCkCa2WeBN_R_1sWpAjy17pVxjqh-KrmO_JPO2umGvIRY_EDFEqXxlFFZOOgJ7bxmsd7JKHNFlStm-3AVZY2lUTp8sOFvilScxpOmcH6jRvODmePQZtylpJl5LbRqKShhpnxLcmrlUMQHvS3TbUVkMDXX-ASOsrJ7ZrVtsuYiGkzrxkDe05gEKLsQAy2hmsSRJP6W5GDChvRrcf5C3PcUlUk2HQYj_rKW87CY-3S5QNs1-uxVOIFv7sKxT9ezIMXOn_XwREIbOaBKKncnr9KD42IDjZJWeotrp3JZTshgJqUbDOAlJ_1GRP0MuVB3J_wWXslGGDGnZJc2HemYk64OBN0mjQTCBQ5ltNTVnwWZZOxK0Bk0LnR_kIElPP_3XZbujqI";
const gql_client = new GraphQLClient(process.env.EXPO_PUBLIC_HYGRAPH_URL!, {
  headers: {
    Authorization: `Bearer ${auth_token}`,
  },
});

// Exporting modules
export { gql_client };
